### ISSUE TITLE
How to locate key point on a unlabeled image?

### ISSUE THREAD

**Issue by xray1111** [rusty1s/deep-graph-matching-consensus#10]
Thank you for share such great paper and code!

Somehow I am still a little bit confused after reading the code. You generate the key point features of the training and test dataset using a VGG16 network, this could be done because all datasets key points are labeled. 

Let's assume there is an unlabeled image, say, an image which has a person in it, is there any way to use your model to infer where those body key points are? Or, Do I need to assume that the key points have already been located but the label name of the points are unknown, thus we can use your model to match the label name to each key point?

**Comment by rusty1s** [comment]
The task we evaluate in the paper solely involves the matching procedure of given keypoints with unknown labels. In order to develop a complete pipeline, one usually combines a keypoint detector with a graph matching algorithm.

**Comment by xray1111** [comment]
Thank you for the prompt response!
