### ISSUE TITLE
Generating Visualizations 

### ISSUE THREAD

**Issue by xun468** [rusty1s/deep-graph-matching-consensus#12]
Hi! I was wondering if you have a script to generate visualizations like in the qualitative results section of the paper? I am struggling to recover the original images from the torch-geometric dataset.

**Comment by rusty1s** [comment]
No script at hand for this at the moment, but each graph should come with an attribute `name` which denotes the original filename of the image.

**Comment by xun468** [comment]
Thanks! I finally managed to get around to it and generated some visualizations of my own. If anyone else needs it, the name and pos attributes can be used to get the original filenames and positions of the nodes for the willow data.
