### ISSUE TITLE
Regarding semi-supervised training

### ISSUE THREAD

**Issue by MLbyML** [rusty1s/deep-graph-matching-consensus#13]
Hello Matthias @rusty1s, 

Thanks for an amazing code base here and with PyTorch Geometric.

I have a small query regarding using the code and not an issue as such: my use case concerns semi-supervised training, where I have two sets of graphs, with each graph containing roughly 300 nodes each  but GT correspondence is available for a subset of nodes only (<20). As inspiration, I began to look at how the [dbp15k](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/dbp15k.html#DBP15K) dataset class is written since this concerns semi supervised setting as well. 

Am I right in believing that essentially I need to pass the indices of the nodes for which GT correspondence is available, in the 2 x N `y_train` tensor variable?  So something like `y_train = [[12, 23, 90, 310, 5, ...], [4, 23, 87, 21, 98, ...]]` would work where the first row contains the index of the node in the moving graph and the second row is the index of the node in the fixed graph,  or am I misunderstanding how this variable is constructed? 

Thank you!

**Comment by rusty1s** [comment]
Yes, this is exactly how you would do it :)

**Comment by MLbyML** [comment]
Thank you!
