### ISSUE TITLE
CUDA out of memory for DBP15K example

### ISSUE THREAD

**Issue by xh3204** [rusty1s/deep-graph-matching-consensus#4]
There is a "**CUDA out of memory**" error arising when we run the DBP15K example. The system hint that the error happens in the "**\_\_top_k\_\_**" function of the **dgmc.py** file. We find that this function needs to establish a matrix space with the shape of (1,n_s,n_t,d), where n and d are the node number and dimension respectively. This is too huge to create. When we modify the function to standard matrix multiplication, this error is repaired. Although I think this modification is equivalent to the original function, I don't know whether this violates your original code design.
![image](https://user-images.githubusercontent.com/37682811/83743917-f937ba80-a68d-11ea-8127-db60bde5bcbb.png)

**Comment by rusty1s** [comment]
That is indeed more memory-friendly. I changed it according to your suggestions. For DBP15K, it is advised to make use of `keops` though for even less memory consumption.
