### ISSUE TITLE
A minor mistake？

### ISSUE THREAD

**Issue by YuYanXiaoJi** [rusty1s/deep-graph-matching-consensus#7]
Hi!
Thank you for sharing your code. I notice a minor mistake in your code when you extract features from a pre-trained VGG16.

Source code of pascal.py

```
vgg16_outputs = []
def hook(module, x, y):
     vgg16_outputs.append(y)

vgg16.features[20].register_forward_hook(hook)  # relu4_2
vgg16.features[25].register_forward_hook(hook)  # relu5_1
```

```
out1 = F.interpolate(vgg16_outputs[0], (256, 256), mode='bilinear',align_corners=False)
out2 = F.interpolate(vgg16_outputs[0], (256, 256), mode='bilinear', align_corners=False)
```
https://github.com/rusty1s/pytorch_geometric/blob/df0612bca76b14464b13c86759eec0c56ebc8154/torch_geometric/datasets/pascal.py#L226

The out2 is edge features from vgg16_outputs[1] ?

Anyway your code helps me a lot. ^_^

Thanks,
Qiafanqie

**Comment by rusty1s** [comment]
Can you clarify on what is the exact issue?

**Comment by YuYanXiaoJi** [comment]
Hi, I see you register two hooks. So why get bilinear interpolation for out2 from vgg16_outputs[0] but not vgg16_outputs[1] ? thanks

**Comment by YuYanXiaoJi** [comment]
> 
> 
> Can you clarify on what is the exact issue?

Hi, I see you register two hooks. So why get bilinear interpolation for out2 from vgg16_outputs[0] but not vgg16_outputs[1] ? thanks

**Comment by rusty1s** [comment]
Oh, I see, you're right! That is a mistake. Thank you, this is now fixed.
